# Site settings
title: WILL Website Manual
header-img: ""
description: "How to use the WILL Website"
baseurl: "/sitemanual/"
urlimg: "/sitemanual/assets/img/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["README.md"]