# Site settings
title: WILL Website Manual
header-img: ""
description: "How to use the WILL Website"
baseurl: "/sitemanual/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["README.md"]